### ISSUE TITLE
setup travis ci build system.

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#100]
Should solve persistent problems like https://github.com/indic-dict/stardict-sanskrit/issues/99#issuecomment-462053646 .

**Comment by vvasuki** [comment]
Done. https://travis-ci.com/indic-dict/

**Comment by drdhaval2785** [comment]
Well done. If I understand correctly, whenever a user changes babylon file here, the results would be reflected in stardict updater app automatically after this build. Is my understanding correct?

One more question - If I change dictionary X, would only dictionary X related stuff will be regenerated or whole repository will be rerun? If second, we can optimize it and make it first option.

**Comment by vvasuki** [comment]
yes, should be option 1. please monitor and report bugs though.
