### ISSUE TITLE
MW - new version from Cologne

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#102]
There are two major enhancements from the current version available via stardict-dictionary-updater.
1. Conversion to IAST from non-standard Anglisized Sanskrit. See  #97.
2. Subheadwords made full fledged headwords.

As MW is highly used dictionary, I have kept it separate in [mw-cologne](https://github.com/indic-dict/stardict-sanskrit/tree/master/sa-head/en-entries/mw-cologne).

@vvasuki may like to see whether we want to replace the old outdated (but visually slightly more attractive) versions of MW with the current one or not.

**Comment by vvasuki** [comment]
All right - deleting mw-sa. Keeping mw-1872, which seems to be different. For example, contrast:
```
From mw-1872
वनिका

वनिका,
f. a little wood, grove, (in अशोक-व्º, a grove
of Aśoka trees; also अशोक-वनिक, अम्, n.)
```
with
```
From mw-cologne
वनिका

वनिका f. a little wood, grove, MBh.; R. &c. (only in अशोक-व्°; once in R. -वनिक n.)
```
