### ISSUE TITLE
Ayurveda nighantus

### ISSUE THREAD

**Issue by damooo** [indic-dict/stardict-sanskrit#103]
many are available at http://niimh.nic.in/ebooks/e-Nighantu/?mod=read, seems can be done easily.

**Comment by damooo** [comment]
And this database, http://envis.frlht.org/implad with indian languages names for each plant/dhatu used in ayurveda, and geographic distribution of them, links to external dbs, etc.
same db available at http://www.medicinalplants.in/ too.

**Comment by vvasuki** [comment]
There are stubs in https://github.com/indic-dict/stardict-sanskrit/tree/master/sa-Ayurveda - but no progress in years.

**Comment by damooo** [comment]
will add them, from next monday onwards anna..

**Comment by vvasuki** [comment]
Ah - in that case, please move sa-Ayurveda and future such work to https://github.com/indic-dict/stardict-ayurveda

**Comment by damooo** [comment]
Ok anna.
