### ISSUE TITLE
ekaksharanamamala of sadhukalashagani added

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#106]
After a lot of time I could actually pursue my interest in https://github.com/indic-dict/stardict-sanskrit/issues/75 .

Out of so many Sanskrit koshas which require digitization, annotation and further processing, I have taken a small 50 verses dictionary and completed the whole cycle from OCR / typing, editing, scripts for cleaning and creation of babylons.

@vvasuki, please add this dictionary to stardict-sanskrit-updater.

Location is in sa-head/sa-entries.

If there is any feedback, let me know, as this is the first time I am trying to annotate a Sanskrit kosha de novo.

There are many more koshas on the way in different stages of development.

**Comment by vvasuki** [comment]
Nice!

Added processed files.
Please follow naming convention, as illustrated by the below fix:
```
ekaksharanamamala-sa/ekaksharanamamala.babylon => ekAkSharanAmamAlA/ekAkSharanAmamAlA.babylon
```

**Comment by vvasuki** [comment]
अस्य ग्रन्थस्याङ्कीकरणं (digitization) कथं कृतम्? तथा babylon-सञ्चिकासृष्टिः? अपि भृत्या नियुक्ताः? कियद्वेतनम्? इति मम कौतूहलम् एतादृशकार्यसिसाधयिषया।

**Comment by drdhaval2785** [comment]
Thanks @vvasuki , I could use the stardict on my android phone without any hassle.

Will follow the naming convention mentioned above.
As regards the question regarding digitization and babylon generation etc., will send a private mail to you.
