### ISSUE TITLE
Scrape rAmakRShNamaTha hinduism encyclopedia

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#110]
http://eoh.rkmathbangalore.org/listing/alphabet/D

**Comment by damooo** [comment]
https://drive.google.com/open?id=14SzoW5pwgVse2yVEGFgdvjH3gsRT10fz

contains script scrape_rkencp.py 
can be run as `python3 scrape_rkencp.py <bl_target_file> <cache_folder> <use_cache>` all three args are optional.
folder contains scraped babylon file.

**Comment by vvasuki** [comment]
Thanks @damooo ! Deploymed successfully after some corrections to my script  - https://travis-ci.com/indic-dict/stardict-sanskrit-kAvya/builds/135818686 .
