### ISSUE TITLE
abhidhAnaratnamAlA of halAyudha added

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#114]
https://github.com/sanskrit-kosha/kosha/tree/master/abhidhanaratnamala_halayudha is the source.
Added via commit https://github.com/indic-dict/stardict-sanskrit/commit/11917cbaabe6bd5818e60ea9cc1ac001579867b7

Will keep on updating the dict as and when there are some worthwhile changes.

I am not sure what is the process to create the stardict files from babylon nowadays in this repository. So noting down the issue here for necessary action, @vvasuki .

**Comment by vvasuki** [comment]
@drdhaval2785 - Please rename to abhidhAnaratnamAlA/abhidhAnaratnamAlA.babylon (note the case). Dict files should then be automatically generated in the gh-pages branch. If that does not happen for some reason, please let me know.

**Comment by drdhaval2785** [comment]
After renaming as suggested, the stardict files get generated. But it seems to have some error. I amnot able to see the entries in my mobile after downloading.

I checked up the travis build.
And found the following error in build. No other file seems to be affected by it.
```
 111 --- stdout excerpt: 
Same word: अनिरुद्धSame word: एधSame word: आसवSame word: मधु
04:33:43 stardict_sanskrit.DictionaryFolder 112 --- stderr excerpt: 
```

When I built the stardict on my local machine, I also got the same error.
```
Building...
Same word: अनिरुद्ध
Same word: एध
Same word: आसव
Same word: मधु
Same word: लिपि
Over
wordcount: 2169
synwordcount: 5732
Done!
```

**Comment by drdhaval2785** [comment]
The stardict files generated locally seem to work in my local stardict in ubuntu.

**Comment by drdhaval2785** [comment]
https://sanskrit-coders.github.io/dictionaries/formats/#dictionary-making-tips seems to know this bug.
For synonymic dictionaries / homonymic dictionaries, duplicate headwords are going to be a frequent issue.
Better we use some lower version of stardict-tools to overcome this issue.

**Comment by vvasuki** [comment]
मम सङ्गणके सम्यग् दृश्यते।

![image](https://user-images.githubusercontent.com/2664797/104887708-bf53c400-5991-11eb-9a4e-119fdc83aa44.png)

एध-शब्द एवम्

- 
```
एध

एध, तर्पण, इन्धन, एध, समिध्, इध्मन्
एधस्तर्पणमिन्धनमधः समिदिध्म इत्यभिन्नार्थाः ।
verse 1.1.1.69
page 0009
```

**Comment by vvasuki** [comment]
Entry for एध in babylon looks like this:

```

एध|तर्पण|इन्धन|एध|समिध्|इध्मन्
एध, तर्पण, इन्धन, एध, समिध्, इध्मन्<BR>एधस्तर्पणमिन्धनमधः समिदिध्म इत्यभिन्नार्थाः ।<BR>verse 1.1.1.69<BR>page 0009
```

This is definitely wrong. Babylon producer script should not duplicate headwords like that.

**Comment by vvasuki** [comment]
Also, I recommend using - instead of `_` in 

```
अनिरुद्ध|काम_सूनु|अनिरुद्ध|उषारमण
अनिरुद्ध, काम_सूनु, अनिरुद्ध, उषारमण<BR>अनिरुद्धश्च तत्सूनुरुषारमण इष्यते ॥ ३४ ॥<BR>verse 1.1.1.34<BR>page 0005
```

**Comment by drdhaval2785** [comment]
Thank you @vvasuki for drawing my attention that this is the case of Same key in `SAME LINE`.
I used to think that it is creating problem because of same key in two different entries.

**Comment by drdhaval2785** [comment]
Now this issue is resolved.

I ran into another issue. 
I am able to search for words in Devanagari in my mobile, but I am unable to search in itrans. abhidhAnaratnamAlAfinal.babylon seems to have with itrans, but EBDIC is not showing anything when I search for anything in itrans. 

Is it a stardict reader issue or something to do with process, @vvasuki ?

**Comment by vvasuki** [comment]
> I ran into another issue.
> I am able to search for words in Devanagari in my mobile, but I am unable to search in itrans. abhidhAnaratnamAlAfinal.babylon seems to have with itrans, but EBDIC is not showing anything when I search for anything in itrans.
> 
> Is it a stardict reader issue or something to do with process, @vvasuki ?

Looks like an EBDIC issue. Goldendict desktop seems fine:

![image](https://user-images.githubusercontent.com/2664797/104943960-85f47600-59dc-11eb-9195-3c17d0aa50c4.png)

**Comment by drdhaval2785** [comment]
As this does not affect multiple users, I am closing this issue. If anyone gets into the same problem, we can reopen it.

**Comment by vvasuki** [comment]
Seems to be a real bug (upon examining the misnamed babylon final files in gh-pages branch.)

**Comment by vvasuki** [comment]
Should be fine now. @drdhaval2785  please reopen if it is not so.

**Comment by drdhaval2785** [comment]
Works well.
