### ISSUE TITLE
Missing stardict-tools in github action.

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#117]
The commit https://github.com/indic-dict/stardict-sanskrit/commit/c557707a4d018aae74dfd3524f44c5baaf2b89e5 which has the Cologne dictionaries updated till 04 April 2021 ran into the following problem on github issues.
It seems that stardict-tools has been removed from apt-get .

```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package stardict-tools
Error: Process completed with exit code 100.
```

**Comment by vvasuki** [comment]
Solved by sticking to 18.04 ubuntu.
