### ISSUE TITLE
Non standard headwords in cologne dicts

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#119]
Some cologne dicts produce non standard headwords such as the lazy anusvAra below:

```
अंक
अंक m. 1. number. 2. issue (of a magazine, newspaper). 3. act (of a play).

अंकगणित
अंकगणित n. arithmetic.
```

This impedes lookup and cross-referencing. @drdhaval2785 - could you ensure that your scripts convert headwords to standard forms (indic_transliteration has functions for this which you could call - see https://github.com/sanskrit-coders/indic_transliteration/blob/964f407b559d93693fba16229a6cd25b98c53661/tests/sanscript/brahmic_test.py#L10)?

**Comment by drdhaval2785** [comment]
I am not sure what is expected.
Do you want अंक to अङ्क ?

What is non-standard in अंक?

**Comment by vvasuki** [comment]
> I am not sure what is expected.
> Do you want अंक to अङ्क ?
> 

Exactly.

> What is non-standard in अंक?

Other dicts use अङ्क, as is typical of modern printed Sanskrit works.

**Comment by drdhaval2785** [comment]
Every dictionary which has अंक also has अङ्क as an alternate headword. 
Therefore, they will always be found by either of the keys.
