### ISSUE TITLE
Add correction links to cologne dicts

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#122]
Suppose I am reading kalpadruma dict entry for tulasii and notice some text with several typos: " पद्मपुराणमते जलन्धरपत्नीवृन्दालावण्यदर्श- नेन विष्णुर्मुग्धः । तन्मोहवारणार्थं देवा महा- देवशरणङ्गताः । महादेवस्तानुवाच मायामारा- धय । ते मायां तुष्टुयुः माया तानुवाच अहं रजः- " . If there were a link beneath the entry to take me directly to a github page, I would fork, do the correction and send a PR.

**Comment by drdhaval2785** [comment]
I did not understand the question properly.

When you say, "I am reading..", what exactly do you have in mind?
1. Reading on some stardict viewer or 
2. Reading on Cologne website ?

**Comment by drdhaval2785** [comment]
In both the cases, the best way to help would be to make necessary corrections in the following repository in the following location.
https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02  and create a PR.
We would be able to merge it very fast.

If you or anyone is interested in correction submission on mass scale, I would gladly help setting up things.

**Comment by vvasuki** [comment]
> 1. Reading on some stardict viewer or

Given that I opened the issue in **stardict**-sanskrit - On a stardict viewer (mostly on my computer, where typing would not be a chore) .


Rather than at a "mass scale" by a single person, we should should shoot for "mass scale" by crowd-sourcing. Casual stardict users should be able to contribute. Currently stardict users basically fret and ignore the errors. https://raw.githubusercontent.com/sanskrit-lexicon/csl-orig/master/v02/skd/skd.txt is too huge - it should be split to one file per entry, and that file's github edit path should be linked from the corresponding stardict entry.

**Comment by funderburkjim** [comment]
> Casual stardict users should be able to contribute

Nice idea.

**Comment by drdhaval2785** [comment]
@vvasuki 
Can you please test the following dictionary for the suggested features?
indic-dict/stardict-sanskrit/sa-head/en-entries/Meulenbeld-Sanskrit-Names-of-Plants 

It seems to work fine on my android phone.

**Comment by vvasuki** [comment]
Looks beautiful - 
![image](https://user-images.githubusercontent.com/2664797/135839666-8d4ad1ed-25a5-4891-9904-d9a60e996cab.png)

Hope I'll be able to correct kalpadruma in devanAgarI though!

**Comment by drdhaval2785** [comment]
All regenerated.
Not sure about MW. All other dicts done. Kindly check.

**Comment by funderburkjim** [comment]
Tried this with colordict on  Android tablet (which I have not used for probably a couple of years).

First comment -  was able to figure out how to update the dictionaries fairly easily, and all went smoothly.  
Also getting information for an entry is straightforward.
The scanned image link worked perfectly.

Also tried Correction.

When pressed 'Correction submission: guru:7025' for Macdonell, I see a 'csl-lnum' Github page.   But was shy about what to do next. If I really had a correction, what would I do to submit the correction?  And what pipeline would the
submitted correction enter?

Incidentally, didn't see a correction submission link (or a scan page link) under MW dictionary for guru.

**Comment by drdhaval2785** [comment]
> If I really had a correction, what would I do to submit the correction?

You would click on 'edit' button on csl-lnum page of guru of MD. Make necessary changes (if you have access rights to the repository).
If you do not have access rights, you would clone and create a PR. 

> MW dictionary for guru.

MW does not have this facility yet. I am yet to upload ig. Size of file exceeded 100 MB after addition of links. Will resolve and put to use soon.

**Comment by drdhaval2785** [comment]
> And what pipeline would the submitted correction enter?

We can merge the PR, if correction is found OK.
I will write a script to carry changes from a given lnum of a given dictionary to csl-orig/v02/xxx/xxx.txt file. That will carry the change made at csl-lnum repo to csl-orig. 
The idea of csl-lnum was to give a chewable bite size to csl-orig.

**Comment by drdhaval2785** [comment]
The links have been added to [csl-ldev](https://github.com/sanskrit-lexicon/csl-ldev/) repository. 
This gives correction facility in Devanagari for Devanagari content.
The issue is closed now.
