### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#123]
I recently refactored the code which was generating babylon files from Cologne Sanskrit dictionaries. I randomly tested compiling stardict files from some of these babylons. It did not give errors
I uploaded the new babylon files on stardict-sanskrit repository. After an hour or so, all the runs failed. 

It seems that some of them were due to time-out.

**Comment by drdhaval2785** [comment]
It subsequently passed the run, but it requires to be seen what caused such a timeout.

**Comment by vvasuki** [comment]
Thanks for the record. Saving my email message as well and closing for now:

> Not sure what was slowing it down - extended time-out to 2h, but the job finished in some 40 minutes this time around - https://github.com/indic-dict/stardict-sanskrit/runs/3774672496?check_suite_focus=true .
