### ISSUE TITLE
Git lfs in Github Actions

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#125]
When I rerenerated mw-cologne.babylon and stored it via git lfs, the resultant stardict file became 0 MB. 

I tried with tweaking workflow yaml file, but no change in result. Maybe we need to find out a way  out.

**Comment by vvasuki** [comment]
> I tried with tweaking workflow yaml file, but no change in result. Maybe we need to find out a way out.

Try printing a few lines with `head mw-cologne.babylon` to confirm that the babylon file was actually retrieved properly from git lfs

**Comment by drdhaval2785** [comment]
printing with head gives the following output, which tallies with the actual file uploaded.
```
#stripmethod=keep
#sametypesequence=h

अ
1. अ the first letter of the alphabet<BR><a href="https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW&page=1,1" target="_blank">Scan page : 1,1</a><BR><a href="https://github.com/sanskrit-lexicon/csl-ldev/blob/main/v02/mw/1.txt" target="_blank">Correction submission : a, 1</a>

अ
 the first short vowel inherent in consonants.<BR><a href="https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW&page=1,1" target="_blank">Scan page : 1,1</a><BR><a href="https://github.com/sanskrit-lexicon/csl-ldev/blob/main/v02/mw/1.1.txt" target="_blank">Correction submission : a, 1.1</a>
```

**Comment by drdhaval2785** [comment]
log file
```
03:15:49 stardict_sanskrit.DictionaryFolder 98 --- babylon: Some(2021-10-06_00-16-23Z), git file: Some(2021-10-06_00-16-23Z), sourceFIle: /home/runner/work/stardict-sanskrit/stardict-sanskrit/sa-head/en-entries/mw-cologne/mw-cologne.babylon
03:15:49 stardict_sanskrit.batchProcessor$ 39 --- Tar file for mw-cologne is not outdated. Not overwriting.
03:15:49 stardict_sanskrit.GithubRepo 70 --- Downloading https://raw.githubusercontent.com/indic-dict/stardict-sanskrit/gh-pages/sa-head/en-entries/tars/mw-cologne__2021-10-06_00-16-23Z__0MB.tar.gz to /home/runner/work/stardict-sanskrit/stardict-sanskrit/sa-head/en-entries/tars/mw-cologne__2021-10-06_00-16-23Z__0MB.tar.gz
```

Tar file not being outdated. What does this mean?

**Comment by vvasuki** [comment]
> log file
> 
> ```
> 03:15:49 stardict_sanskrit.DictionaryFolder 98 --- babylon: Some(2021-10-06_00-16-23Z), git file: Some(2021-10-06_00-16-23Z), sourceFIle: /home/runner/work/stardict-sanskrit/stardict-sanskrit/sa-head/en-entries/mw-cologne/mw-cologne.babylon
> 03:15:49 stardict_sanskrit.batchProcessor$ 39 --- Tar file for mw-cologne is not outdated. Not overwriting.
> 03:15:49 stardict_sanskrit.GithubRepo 70 --- Downloading https://raw.githubusercontent.com/indic-dict/stardict-sanskrit/gh-pages/sa-head/en-entries/tars/mw-cologne__2021-10-06_00-16-23Z__0MB.tar.gz to /home/runner/work/stardict-sanskrit/stardict-sanskrit/sa-head/en-entries/tars/mw-cologne__2021-10-06_00-16-23Z__0MB.tar.gz
> ```
> 
> Tar file not being outdated. What does this mean?

Useful logs there. So, if you see, timestamp for `mw-cologne__2021-10-06_00-16-23Z__0MB.tar.gz` matches the timestamp for the babylon file `babylon: Some(2021-10-06_00-16-23Z)` (deduced by querying github commits <-- don't know if [this logic](https://github.com/indic-dict/dict-tools/blob/58664f86d8ede77d7935c36068567555881beb3f/src/main/scala/stardict_sanskrit/GithubRepo.scala#L82) breaks down when LFS is used). So, the dict maker [concludes](https://github.com/indic-dict/dict-tools/blob/2adb55a6ba7bca1b1d797e5011a686dd3f6585fa/src/main/scala/stardict_sanskrit/batchProcessor.scala#L39) that there's no need to generate mw-cologne...tar.gz again.

**Comment by vvasuki** [comment]
@drdhaval2785 

Here's a mail I got:

```
We wanted to let you know that you’ve used 80% of your data plan for Git LFS on the organization indic-dict. No immediate action is necessary, but you might want to consider purchasing additional data packs to cover your bandwidth and storage usage:

  https://github.com/organizations/indic-dict/billing/data/upgrade

Current usage as of 14 Oct 2021 02:28AM UTC:

  Bandwidth: 0.84 GB / 1 GB (84%)
  Storage: 0.11 GB / 1 GB (11%)
```

Looks like should consider reverting this LFS change. What do you think?

**Comment by vvasuki** [comment]
Obsolete.

**Comment by drdhaval2785** [comment]
Yes. Obsolete. An experiment without success.
