### ISSUE TITLE
Add Apte Sanskrit - Hindi dictionary

### ISSUE THREAD

**Issue by chandrasekharanr** [indic-dict/stardict-sanskrit#142]
It is available in https://sanskrit.uohyd.ac.in/scl/

Please look here for example -
https://sanskrit.uohyd.ac.in/cgi-bin/scl/MT/options1.cgi?word=%E0%A4%A6%E0%A4%BF%E0%A4%B5%E0%A5%8D&outencoding=DEV

I think Arun from Ambuda is already pursuing this. But creating this to track the progress or pick it up if that does not materialize.

**Comment by vvasuki** [comment]
@akprasad informs me that he has received the data from another source. Once he ingests, we (babylon/ stardict users) should be good to go (modulo https://github.com/sanskrit/ambuda/issues/5 )

**Comment by vvasuki** [comment]
shrI @akprasad shared the file he received. It's added now. 

example entry - 

```
From आप्टे - हिन्दी (sa-hi)Collapse article
कर्तव्यम्

19205	नपुं*	H1	-	KN	कृ-तव्यत्
"जो होना चाहिए, धर्म, आभार"
```
