### ISSUE TITLE
Add: Bhūtasaṃkhyā Dict Collected by K.P. Shukla (already proofed) 

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-sanskrit#154]
https://ambuda.org/proofing/list-of-word-numerals-bhutasamkhya/

Taken from the appendix of this book. Reportedly the most exhaustive list of bhUtasaMkhyA words currently available.

https://www.worldcat.org/title/841881528

**Comment by vvasuki** [comment]
Done
