### ISSUE TITLE
To add: Laukika-nyāya-kośa

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-sanskrit#160]
https://ambuda.org/proofing/laukika-nyaya-kosa/

Please include ambuda in the dict name when you create it:
ambuda-laukika-nyaya or similar.

**Comment by vvasuki** [comment]
Done, thanks!

Acknowledged ambuda in the description - 

![image](https://github.com/indic-dict/stardict-sanskrit/assets/2664797/9f500d71-367e-4e1e-8d3e-18d6794a2d24)


Installation and lookup program user interface limitations don't allow for too much clutter in the short name field. Hence, for all our dicts (including those from DCS), we mention only whatever is needed for clear identification/ search/ classification (dict name, author name/ affiliation) during lookup, grouping etc..
