### ISSUE TITLE
Fill description field for DCS dicts

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#161]
Add something like `#description` below to DCS dicts:

```

#bookname=लौकिक-न्याय-कोशः laukika-nyAya (sa-en)
#stripmethod=keep
#sametypesequence=h
#description=Initial version from https://ambuda.org/proofing/laukika-nyaya-kosa .

```

![image](https://github.com/indic-dict/stardict-sanskrit/assets/2664797/cddf4fc0-fc89-4d61-8497-b80f49e4c033)

**Comment by drdhaval2785** [comment]
All Cologne dictionaries are regenerate with latest data as on 16 June 2023.

I do not have an android system, so not able to check whether the output works well with stardict-dictionary-updater.

**Comment by vvasuki** [comment]
> I do not have an android system, so not able to check whether the output works well with stardict-dictionary-updater.

screenshot was from goldendict on desktop.
