### ISSUE TITLE
Added अभिधानचिन्तामणिशिलोञ्छ by जिनदेव

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#169]
This completes the trio of 
1. अभिधानचिन्तामणि (हेमचन्द्र) 
2. अभिधानचिन्तामणिपरिशिष्ट (हेमचन्द्र) (Addendum by the author in his auto-commentary)
3. अभिधानचिन्तामणिशिलोञ्छ (जिनदेव) (Addendum of left out words by a later scholar)

**Comment by drdhaval2785** [comment]
Same issue as before. Tar is not generated.

**Comment by vvasuki** [comment]
Looks like you've named the folder abhidhAnachintAmaNishilo~nCha . Remove the tilde. Make sure that the filename and dirname match. Then it'll work.

**Comment by drdhaval2785** [comment]
Corrections installed. Regenerated as expected. Closing
