### ISSUE TITLE
Please add from Ambuda: Nyayakosha of Jhalkikar

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-sanskrit#174]
https://ambuda.org/proofing/nyayakosajhal/

**Comment by vvasuki** [comment]
There were about 16 headword markup errors I fixed (don't know if I missed other kinds). 
Would've been nice to add non-mechanically detectable prAtipadikas (like niyantR for niyantA).
Footnote markup could've been better. 
Would've been nice to have the prefaces proofread while at it.  
Anyway, dict should be generated if https://github.com/indic-dict/stardict-sanskrit/actions/runs/7564203570 succeeds
