### ISSUE TITLE
Capeller Sanskrit German added

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#42]
CCS

**Comment by vvasuki** [comment]
19:37:50 stardict_sanskrit.DictionaryFolder 93 --- Making stardict from: /home/travis/build/indic-dict/stardict-sanskrit/sa-head/german-entries/capeller-sanskrit-german/capeller-sanskrit-german.babylon
19:37:50 stardict_sanskrit.DictionaryFolder 95 --- stdout excerpt: 
Error, no new line char after definition line: 90035

**Comment by vvasuki** [comment]
Fixed as in https://github.com/indic-dict/stardict-sanskrit/issues/108
