### ISSUE TITLE
MW English-Sanskrit added

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#48]
MWE

**Comment by vvasuki** [comment]
Good! Once this is fully ready, we can deprecate the older aupAsana version.

An example entry:

> TREE, s. वृक्षः, तरुः m., द्रुमः, पादपः, द्रुः m., वनस्पतिः m., वनराजिः m., क्षितिरुहः, महीरुहः, भूरुहः, फलग्राही m. (न्), फलदः, पल्लवी m. (न्), रोहिः m., अवनिरुट् m. (ह्), अवनिरुहः, स्कन्धी m. (न्), विटपी m., शाखी m., अंह्रिपः, गच्छः, पत्री m., कुठः, कुठः, अगमः, पलाशी m., शालः, सालः, अनोकहः, वानस्पत्यः; ‘a village tree, held in veneration,’ चैत्यः; ‘relating to a tree,’ वार्क्षः -र्क्षी -र्क्षं.

* One can add as headwords various synonymous sanskrit words
* One can separate entries - again with semicolon as a separator.

**Comment by drdhaval2785** [comment]
All these dictionaries will undergo a major revision as soon as Jim
supplies latest XMLs. My local copies of XMLs are at least one and half
year old.

Will consider all suggestions made by you for improvement in babylon when
regenerating.

**Comment by vvasuki** [comment]
A bad entry:
ABHORRENT, a. (Struck with abhorrence) bIBatsAnvitaH -tA -taMविरुद्धः -द्धा -द्धं, अयोग्यः -ग्या -ग्यं, असङ्गतः -ता -तं, असंस्थितः -ता -तं, विपरीतः -ता -तं.

**Comment by vvasuki** [comment]
Retiring the ancient en-head/mw-bi-itrans-dev/ in favor of this.
