### ISSUE TITLE
Rename files only if different from previous version

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#49]
Now we are planning to publish monthly updated version of Cologne dictionaries on stardict. But currently the machine for statdict file generation renames with timestamp every time.

Can you make it to check with the version on machine and change timestamp inly if there is some differrence in it?

If there is no change in dictionary binary files in last month, let it continue to retain its old timestamp.

**Comment by vvasuki** [comment]
Rather, (monthly) updates from the scripts which you'll write should only alter those babylon files which need to be updated [not everything]. Suggested system would be to compare git version - if that's too hard - file size and modification timestamp on one's computer..

**Comment by gasyoun** [comment]
> Suggested system would be to compare git version

Too hard is too easy to say :100:

**Comment by vvasuki** [comment]
> Too hard is too easy to say :100:

That too is easy to say :-D

**Comment by vvasuki** [comment]
@drdhaval2785 An example of the comparisons I'm using to decide whether a given artifact (tar or stardict file etc..) should be updated (from https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/bin/scripts/stardict_sanskrit/Dictionary.scala#L55 ):


```
  def babylonFinalFileNewerThanBabylon(): Boolean = {
    babylonFinalFile.isDefined && (babylonFinalFile.get.lastModified > babylonFile.get.lastModified)
  }

  def tarFileNewerThanIfo(): Boolean = {
    tarFile.isDefined && (tarFile.get.lastModified > ifoFile.get.lastModified)
  }


  def getBabylonFile(): File = {
    if (babylonFinalFile.isDefined) {
      babylonFinalFile.get
    } else {
      babylonFile.get
    }
  }

  def ifoFileNewerThanBabylon(): Boolean = {
    val babFile = getBabylonFile
    ifoFile.isDefined && (ifoFile.get.lastModified > babFile.lastModified)
  }

```

You can do something similar to get things rolling.
Btw, have you considered using scala? I switched from python to scala a long time ago because it is even more declarative and concise.

**Comment by vvasuki** [comment]
https://github.com/indic-dict/dict-tools/issues/1 should fix this.
