### ISSUE TITLE
Add headwords for alternate renderings resulting from यरो द्वे

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit#77]
The optional form आचार्य्य is present in vAcaspatyam and kalpadruma, no आचार्य, as in other dictionaries. This confounds users. I spent quite a while wondering how vAcaspatyam and kalpadruma couldn't have this term.

Solution is to add alternate renderings where they don't exist. Pertinent sUtra-s http://www.ashtadhyayi.com/sutraani/8/4/47   ( @drdhaval2785 fyi) .

**Comment by drdhaval2785** [comment]
Yes. There are many such cases. Some dicts have अंग, some have अंगः, अङ्ग, अङ्गः.
All these need to be normalized. It is already on way. I have created data for this. Pending to upload. I am held up in some other project currently.

**Comment by gasyoun** [comment]
@vvasuki have you seen @drdhaval2785 normalization efforts at https://github.com/sanskrit-lexicon/? 
He has done a lot in this field, documented different standards used. The issue is much wider than just VCP and SKD.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/hwnorm1

This is the repository aiming at normalizing headwords of various Cologne dictionaries. The output of this process has to be used as an input for stardict generation.

**Comment by gasyoun** [comment]
> The output of this process has to be used as an input for stardict generation.

I guess it's harder than it sounds. Any idea where @vvasuki could start at?

**Comment by vvasuki** [comment]
हह।  @gasyoun , don't go randomly volunteering me :-) . I just reported the bug.

@drdhaval2785 Reg. `अंगः, अङ्ग` : Wow! I wouldn't have guessed that sanskrit dicts would be as clumsy/ lazy with devanAgarI as hindI one-s. I remember fixing that with hindI shabdasAgara. 

Also, what is the general approach you're taking? You're _adding_, not _replacing_ headwords, right?

**Comment by gasyoun** [comment]
> I just reported the bug.

It's not a bug. It's a feature of Indian dictionaries :+1: 

> Also, what is the general approach you're taking? You're adding, not replacing headwords, right?

Until now nothing was done.

**Comment by drdhaval2785** [comment]
It is handled now.
I entered dharma and it lead me to both entries of vAchaspatyam and shabdakalpadruma. 
![screenshot_20190210-101239_colordict](https://user-images.githubusercontent.com/5755132/52529686-84b06e00-2d1c-11e9-8c80-09fb9b603232.jpg)

**Comment by drdhaval2785** [comment]
aNga, aMga issue also seems to be sorted out. If any issue remains, can be tracked on separate issue.
![screenshot_20190210-102243_colordict](https://user-images.githubusercontent.com/5755132/52529766-ec1aed80-2d1d-11e9-846f-d6ce994f53d3.jpg)
