### ISSUE TITLE
pending to correct after regeneration

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#81]
Schmidt-Nachtrage-zum-Sanskrit-Worterbuch

10:18:57.450 [main] INFO  stardict_sanskrit.Dictionary - Making stardict from: /home/dhaval/stardict-sanskrit/sa-head/german-entries/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch/Schmidt-Nachtrage-zum-Sanskrit-Worterbuch.babylon_final
```
** (process:13191): WARNING **: Line 28272, bad definition!!!

** (process:13191): WARNING **: Line 28275, bad definition!!!
```
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/360 for reference.

**Comment by drdhaval2785** [comment]
apte-1890

** (process:3469): WARNING **: Line 27639, bad definition!!!

**Comment by drdhaval2785** [comment]
@vvasuki did these errors come up during recent run?

**Comment by vvasuki** [comment]
[logs.txt](https://github.com/indic-dict/stardict-sanskrit/files/2848529/logs.txt)
No - log attached. there was another problem - spurious empty lines at the end of babylon files - which I handled by making my parser smarter.
