### ISSUE TITLE
Stchoupak sanskrit-french dictionary

### ISSUE THREAD

**Issue by frpatte2** [indic-dict/stardict-sanskrit#94]
Bonjour,

I just installed the git pack with all available sanskrit dictionaries. Among them the Stchoupak sanskrit-french dictionary. 
Curiously, the entries have been turned in devanagari script! Why? In the original paper dictionary, the entries are in roman translitteration. 
This dictionary does not work in emacs dictd system: when you enter the "select dictionary" tab, you can see the Stchoupak dictionary, but it is impossible to search a word in it, using devanagari script or roman transliteration (btw: which scheme of translitteration shall we use?).

How can I use this dictionary in emacs. Monier-Williams works fine.

Thank you.

**Comment by vvasuki** [comment]
Bonjour!

> Curiously, the entries have been turned in devanagari script! Why? 

Indian users find it more convenient.

But, there is a roman transliteration also included, which you can note by opening [this file](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-head/french-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon_final).  The transliteration scheme is something called [OPTITRANS v1](https://sanskrit-coders.github.io/site/pages/input/optitrans.html#optitrans-v1).
```
अ|a
१अ-<BR> thème pron., v. इदम्-।

अ|a
२अ<BR> (dev. cons.) अन् (dev. voy.) préf. négatif (privatif, antinomique);<BR> devant noms, rar. devant pronoms et verbes.

अऋणिन्|aRNin
अ-ऋणिन्-<BR> (अ pour अन्) a. libre de dettes.

अंश|aMsha
अंश-<BR> m. part, partie, morceau, division;<BR> part d'héritage;<BR> n. d'un Āditya;<BR> -ई-कृ- partager. °कल्पना- f. assignation d'une part (d'héritage);<BR> °प्रकल्पना- id. °प्रदान- nt. octroi d'une part (d'héritage). °भागिन्- a. qui a une part. °भाज्- ag. qui prend part à. °भूत- a. qui constitue une part de. अंशावतरण- nt. incarnations partielles, n. d'un chap. du MhBh.;<BR> अंशावतार- m. id.

अंशु|aMshu
अंशु-<BR> m. rayon;<BR> -क- nt. pièce d'étoffe, d'habillement, not. jupe;<BR> linge, mousseline. °पट्ट- nt. sorte d'étoffe de soie. °भर्तृ°मालिन्- m. soleil. अंशुकान्त- m. frange (d'une étoffe).

अंशुमन्त्|अंशुमत्|aMshumant|aMshumat
अंशुमन्त्-<BR> a. irradiant;<BR> m. soleil;<BR> petit-fils de Sagara;<BR> n. d'une montagne;<BR> -(अत्)īl. n. d'une rivière.

```

We'd be glad to link an IAST version if you create and host it somewhere.

I used goldendict app on linux - so don't know the answer to the emacs dictd problem.

**Comment by frpatte2** [comment]
Thank you for your answer. About the emacs dictd problem: after some research the problem is an unix dictd format of the index file: as we can see on this golden dict page https://github.com/goldendict/goldendict/wiki/Supported-Dictionary-Formats, the index for goldendict is a .idx format while dictd use a .index format which a human readable format (this format also works with goldendict and stardict).
Is there a way to convert an .idx file into an .index file.
I am sorry to ask this question here but it seems to be impossible to get any information from the dictd development staff: they never answer any mail including mails to subscribe to their mailing list.

Thank you for attention. Regards.

**Comment by vvasuki** [comment]
The simplest thing might be to do the following:
- Start with [this file](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-head/french-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon_final)
- Convert to jargon file (perhaps using a series of regular expression replacements in your favorite text editor). See [here](https://en.wikipedia.org/wiki/DICT#DICT_file_format) for format.
- Used dictfmt to convert the jargon file to a dictd file. See [here](https://en.wikipedia.org/wiki/DICT#DICT_file_format) for command.

Let me know what you end up doing and how it goes!
