### ISSUE TITLE
Diacritical marks for MW dictionary

### ISSUE THREAD

**Issue by chandrasekharanr** [indic-dict/stardict-sanskrit#97]
Need to change the numbers after the English letters to diacritical marks to make it more readable. For example, 

सिच् cl.6 P. A1. ( Dha1tup. xxviii , 140 )

should be 

 सिच् cl. 6 P. Ā.  (Dhātup. xxviii, 140 )

**Comment by drdhaval2785** [comment]
Currently I am in process of regenerating the MW based on data which was converted to IAST for all dictionaries at Cologne. All cases where there was number after letters would be cleared then. You will have to wait till 31st Jan or so.

**Comment by funderburkjim** [comment]
> All cases where there was number after letters would be cleared then

We Hope!
