### ISSUE TITLE
Feature request : wild card search

### ISSUE THREAD

**Issue by chandrasekharanr** [indic-dict/stardict-sanskrit#98]
If a wildcard search feature (like https://github.com/sanskrit-lexicon/Cologne/issues/241) is needed, it is probably something that the app (like ColorDict, Goldendict) has to offer.

In any case, it will be a "nice to have" feature.

**Comment by drdhaval2785** [comment]
Put feature request mail to ColorDict app maintainers. Not much that we can do in this regard.

**Comment by vvasuki** [comment]
Actually, my personal favorite app - ebdic, which one can install from https://apkpure.com/ebdic/com.twn.ebdic , lets one search based on suffix, prefix and substrings. Check it out.
