### ISSUE TITLE
cologne regeneration February 2019

### ISSUE THREAD

**Issue by drdhaval2785** [indic-dict/stardict-sanskrit#99]
All dictionaries of Cologne have been regenerated into babylon as on 8th Feb 2019.
@vvasuki 
1. Add me here, so that I can push the new babylons.
2. I am on a Windows machine and despite my best efforts, I am not able to run the makefiles. So once I upload the babylons, would you run the makefiles / scala code on my behalf and do the rest of the stuff?

**Comment by vvasuki** [comment]
Changed your role in https://github.com/orgs/indic-dict/people to owner - you can add yourself anywhere necessary

**Comment by drdhaval2785** [comment]
tried enough time in even ubuntu machine too.
Not succeeded.
Kindly run on my behalf.

Instructions seem slightly clumsy.
e.g. sanskritnlpjava is required, but not noted.
gtk2.0 seems required for compiling stardict.

**Comment by vvasuki** [comment]
Done - plz check.

No separate package called sanskritnlpjava should be required ... Anyway opened https://github.com/indic-dict/stardict-sanskrit/issues/100 for a sustainable solution.

**Comment by drdhaval2785** [comment]
Seems to work. The updater shows newly generated dicts
